[package]
name = "BTests"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
protobuf_strict = { git = "https://github.com/Jasperav/protobuf_strict.git" }